site_name: pulseforge
site_url: https://geeks-trident-llc.github.io/pulseforge/
repo_url: https://github.com/Geeks-Trident-LLC/pulseforge
repo_name: Geeks-Trident-LLC/pulseforge

theme:
  name: material
  features:
    - navigation.instant
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - content.code.annotate
    - toc.integrate
  palette:
    - scheme: default

plugins:
  - search

markdown_extensions:
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: ["."]
      check_paths: true

nav:
  - Home: index.md
  - Changelog: changelog.md
